### ISSUE TITLE
Crash trying to uninstall app

### ISSUE THREAD

**Issue by Fleker** [ITVlab/TvAppRepo#26]
Crash log

    Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.PackageInfo.packageName' on a null object reference
       at news.androidtv.tvapprepo.utils.PackageInstallerUtils.uninstallApp(Unknown Source)
       at news.androidtv.tvapprepo.fragments.AppDetailsFragment$ItemViewClickedListener.onItemClicked(Unknown Source)
       at news.androidtv.tvapprepo.fragments.AppDetailsFragment$ItemViewClickedListener.onItemClicked(Unknown Source)
       at android.support.v17.leanback.widget.DetailsOverviewRowPresenter$ActionsItemBridgeAdapter$1.onClick(DetailsOverviewRowPresenter.java:90)
       at android.view.View.performClick(View.java:5198)
       at android.view.View.onKeyUp(View.java:9879)
       at android.widget.TextView.onKeyUp(TextView.java:6251)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2664)
       at android.view.View.dispatchKeyEvent(View.java:9234)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at android.support.v17.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:843)
       at android.support.v17.leanback.widget.HorizontalGridView.dispatchKeyEvent(HorizontalGridView.java:50)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at android.support.v17.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:843)
       at android.support.v17.leanback.widget.VerticalGridView.dispatchKeyEvent(VerticalGridView.java:40)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2395)
       at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1727)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2725)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4273)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4235)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3783)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3836)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3802)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3931)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3810)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3988)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3783)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3836)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3802)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3810)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3783)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3836)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3802)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3964)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4125)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2264)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1885)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1876)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2241)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5482)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Fleker** [comment]
Fixes the crash
