### ISSUE TITLE
crashes on new shield tv

### ISSUE THREAD

**Issue by ScottMccay** [ITVlab/TvAppRepo#67]
app repo crashes on new 7,01 shield experience android oreo 8.0 when you click create shortcut

**Comment by xstar97** [comment]
Logs??

**Comment by ScottMccay** [comment]
i tried reinstalling it and install fails

**Comment by ScottMccay** [comment]
dont know how to get logs

**Comment by ScottMccay** [comment]
we need a serious update :)

**Comment by ScottMccay** [comment]
just figured out it would not install was my fault but it still wont create shortcut its not compatible with oreo

**Comment by Fleker** [comment]
What happens exactly?

**Comment by ScottMccay** [comment]
load the app and select an app to create shortcut then click on create shortcut and it crashes back to home screen

**Comment by ScottMccay** [comment]
man i really need a working copy for oreo

**Comment by Fleker** [comment]
Can you get logs through ADB to see where the error is coming from?

**Comment by morphext** [comment]
Hi there. I don't have a log for this issue. What I'm suspecting the issue is is the app uses the apps row in android 7. Meanwhile, android 8 uses Channels, which is therefore causing the app to not work on the newest update. Just my thought.

**Comment by ScottMccay** [comment]
no there are still app tiles under all apps

**Comment by ScottMccay** [comment]
for those waiting on an update
http://atvlauncher.trekgonewild.de/

**Comment by Fleker** [comment]
The base framework hasn't changed enough that generating app shortcuts would break. Using the new channels UI would be a nice feature request, but if there are no logs or stacktraces to identify the issue it would be difficult to create a patch.

**Comment by ScottMccay** [comment]
well got an update to a system function for the leanback and now its working LOL whats weird is it was talkback that was updated but the description did say it was part of leanback launcher :)

**Comment by ScottMccay** [comment]
it also appears that it works on some apps but not on others strange

**Comment by madusmacus** [comment]
@sterno1966 thank you for that workround pain in the bum but works :-)

UK just got nvidia shield update and saddly some apps it cant make apk for
1) chrome and gmail fail with instant crash back to launcher (cant understand how to get logs for you sorry)
2) button remapper and microsoft rdk create apk fine but cant auto install as tvapprepo is not in the list to alow that option

still manualy installing them works ok 

weird i think nvidia has got it in for your app heheheheh

**Comment by lekiend** [comment]
I Have the same issue. Do not work anymore on NVIDIA SHIELD :-(

**Comment by cecoates** [comment]
It only occurs with certain apps. So far for me it doesn't work on:

Chrome
Hulu Plus
Series Mate
Lifx
SeriesGuide
Amazon AppStore

Same behavior as above. It crashes back to the home screen (really, it crashes back to the last window you had open. If you multi-task over to TV App Repo, it'll crash back to the last app you were running.)

No 20 seconds message, just "Create Shortcut" and then crash.

**Comment by wiredrunner** [comment]
Same issue since the update.  If the app you want to create the shortcut for has a dark green shaded box under neath the icon in the leanback row where you'd go to create the shortcut clicking on create shortcut brings you back to the home screen - it crashes.  Apps that I had previously successfully created a shortcut for successfully and for whatever reason deleted - that now show that green shaded box (with the app name in it) now crash and no shortcut can be created.  Those boxes under neath the app in the leanback row now has all sorts of colors associated with the apps though it seems to be just those with the green color that fail.  Firefox has a bright blue box, there are some apps that are bright red and one is pistachio green but just those with the dark green won't work and crash tvapprepo.

If someone knows how to produce the logs I would be glad to post them.

Yandex Browser is one. Chrome, Google Drive, Reddit, GMAIL,

**Comment by Fleker** [comment]
It would be very weird if the color of the icon resulted in the app crashing.

To get the logs, you'll need to setup ADB on your computer and then connect to your device and run `adb logcat`

**Comment by wiredrunner** [comment]
As I said it's the color under the icon that has the name of the app etc not the icon itself.  You wrote an app for android tv but from the sounds of it it you don't have an android tv yourself?

**Comment by Fleker** [comment]
I haven't used the app in a while.

**Comment by MartenvanWezel** [comment]
Still happening, FYI. Happy to pull logs if there's some instructions.

**Comment by indigob0y** [comment]
TV App Repo doesn't show in Settings -> Security & restrictions -> Unknown sources. It does seem to sometimes download the generated apk (most often not), but on my Shield TV it doesn't seem to even try to install it as the appropriate dialog window doesn't show up (no crash though). Downloaded apk was in 'Downloads' folder, and I could install it, after giving the proper permissions to 'File Commander'.

### This is what I found in the logs:
(from logcat)

_10-12 22:53:49.077 27642 27642 D GenerateShortcutHelper: {"build_ok":true,"app":{"download_link":"http:\/\/atvlauncher.trekgonewild.de\/download.php?v=5aa34938c0651361660391","name":"Hearthstone","package":"com.blizzard.wtcg.hearthstone","category":"games","logo":"http:\/\/atvlauncher.trekgonewild.de\/showimage.php?v=5aa34938c0651361660391&t=l","intent":"","unique":false,"from_cache":true}}
10-12 22:53:49.078 27642 27642 I PackageInstaller: wget http://atvlauncher.trekgonewild.de/download.php?v=5aa34938c0651361660391
10-12 22:53:49.078 27642 27642 I PackageInstaller: Starting download
10-12 22:53:49.095  1400 20754 E NetworkScheduler: Invalid component specified.
10-12 22:53:49.081   695   766 I chatty  : uid=1000(system) android.anim identical 5 lines
10-12 22:53:49.098   695   766 I WindowManager: B2026652 WAR. Hide the surface news.androidtv.tvapprepo.playstore/news.androidtv.tvapprepo.activities.AdvancedShortcutActivity
10-12 22:53:49.104 27642 27642 E ActivityThread: Activity news.androidtv.tvapprepo.activities.AdvancedShortcutActivity has leaked IntentReceiver tv.puppetmaster.tinydl.PackageInstaller$1@6cdd561 that was originally registered here. Are you missing a call to unregisterReceiver()?
10-12 22:53:49.104 27642 27642 E ActivityThread: android.app.IntentReceiverLeaked: Activity news.androidtv.tvapprepo.activities.AdvancedShortcutActivity has leaked IntentReceiver tv.puppetmaster.tinydl.PackageInstaller$1@6cdd561 that was originally registered here. Are you missing a call to unregisterReceiver()?
10-12 22:53:49.104 27642 27642 E ActivityThread:        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1333)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1114)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1424)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1397)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1385)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:603)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at tv.puppetmaster.tinydl.PackageInstaller.initialize(PackageInstaller.java:101)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at news.androidtv.tvapprepo.download.ApkDownloadHelper.initialize(ApkDownloadHelper.java:22)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at news.androidtv.tvapprepo.download.ApkDownloadHelper.<init>(ApkDownloadHelper.java:17)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at news.androidtv.tvapprepo.utils.GenerateShortcutHelper.downloadShortcutApk(GenerateShortcutHelper.java:106)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at news.androidtv.tvapprepo.utils.GenerateShortcutHelper.access$300(GenerateShortcutHelper.java:36)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at news.androidtv.tvapprepo.utils.GenerateShortcutHelper$6.onResponse(GenerateShortcutHelper.java:170)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at news.androidtv.tvapprepo.utils.ShortcutPostTask$1.onResponse(ShortcutPostTask.java:76)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at news.androidtv.tvapprepo.utils.ShortcutPostTask$1.onResponse(ShortcutPostTask.java:72)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at com.sketchproject.infogue.modules.VolleyMultipartRequest.deliverResponse(VolleyMultipartRequest.java:136)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at com.sketchproject.infogue.modules.VolleyMultipartRequest.deliverResponse(VolleyMultipartRequest.java:31)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at android.os.Handler.handleCallback(Handler.java:789)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at android.os.Handler.dispatchMessage(Handler.java:98)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at android.os.Looper.loop(Looper.java:164)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at android.app.ActivityThread.main(ActivityThread.java:6592)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at java.lang.reflect.Method.invoke(Native Method)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-12 22:53:49.104 27642 27642 E ActivityThread:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-12 22:53:49.115  1400 22387 E NetworkScheduler: Invalid component specified.
10-12 22:53:49.140 23078 23091 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Download/download.phpv=5aa34938c0651361660391.apk
10-12 22:53:49.150 27642 27818 I PackageInstaller: Download request for http://atvlauncher.trekgonewild.de/download.php?v=5aa34938c0651361660391 enqueued
10-12 22:53:49.150 27642 27818 D PackageInstaller: Should be saved to download.phpv=5aa34938c0651361660391.apk_

**Comment by TimetoDance** [comment]
^ Speak for yourself. For some people it just crashes without downloading anything.

**Comment by jordanade** [comment]
Same here on up-to-date Shield:

```
04-09 18:44:29.786 25606 25606 D GenerateShortcutHelper: Loading ad
04-09 18:44:29.789 25606 25606 D ShortcutPostTask: {}
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: --apiclient-1554849869789
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: Content-Disposition: form-data; name="app_name"
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: 
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: SkyTube Extra
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: --apiclient-1554849869789
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: Content-Disposition: form-data; name="app_package"
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: 
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: free.rm.skytube.extra
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: --apiclient-1554849869789
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: Content-Disposition: form-data; name="unique"
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: 
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: false
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: --apiclient-1554849869789
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: Content-Disposition: form-data; name="json"
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: 
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: true
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: --apiclient-1554849869789
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: Content-Disposition: form-data; name="app_category"
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: 
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: apps
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: --apiclient-1554849869789--
04-09 18:44:29.791 25606 25606 D ShortcutPostTask: multipart/form-data;boundary=apiclient-1554849869789
04-09 18:44:29.793 25606 25679 E Volley  : [2723] NetworkDispatcher.run: Unhandled exception java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
04-09 18:44:29.793 25606 25679 E Volley  : java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
04-09 18:44:29.793 25606 25679 E Volley  : 	at android.widget.Toast$TN.<init>(Toast.java:400)
04-09 18:44:29.793 25606 25679 E Volley  : 	at android.widget.Toast.<init>(Toast.java:114)
04-09 18:44:29.793 25606 25679 E Volley  : 	at android.widget.Toast.makeText(Toast.java:287)
04-09 18:44:29.793 25606 25679 E Volley  : 	at android.widget.Toast.makeText(Toast.java:277)
04-09 18:44:29.793 25606 25679 E Volley  : 	at android.widget.Toast.makeText(Toast.java:314)
04-09 18:44:29.793 25606 25679 E Volley  : 	at news.androidtv.tvapprepo.utils.ShortcutPostTask$3.getByteData(ShortcutPostTask.java:129)
04-09 18:44:29.793 25606 25679 E Volley  : 	at com.sketchproject.infogue.modules.VolleyMultipartRequest.getBody(VolleyMultipartRequest.java:98)
04-09 18:44:29.793 25606 25679 E Volley  : 	at com.android.volley.toolbox.HurlStack.addBodyIfExists(HurlStack.java:260)
04-09 18:44:29.793 25606 25679 E Volley  : 	at com.android.volley.toolbox.HurlStack.setConnectionParametersForRequest(HurlStack.java:234)
04-09 18:44:29.793 25606 25679 E Volley  : 	at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:107)
04-09 18:44:29.793 25606 25679 E Volley  : 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
04-09 18:44:29.793 25606 25679 E Volley  : 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
04-09 18:44:29.812 25606 25618 D ViewRootImpl: windowFocusChanged true news.androidtv.tvapprepo
04-09 18:44:29.814 25606 25618 D ViewRootImpl: windowFocusChanged false news.androidtv.tvapprepo
04-09 18:44:29.831  3380  3380 D hwcomposer: hwc_getActiveConfig: returning 0
04-09 18:44:29.852 25606 25606 E ShortcutPostTask: Error: java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
04-09 18:44:29.852 25606 25606 D ShortcutPostTask: com.android.volley.VolleyError: java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
04-09 18:44:29.854 25606 25606 D AndroidRuntime: Shutting down VM
04-09 18:44:29.854 25606 25606 E AndroidRuntime: FATAL EXCEPTION: main
04-09 18:44:29.854 25606 25606 E AndroidRuntime: Process: news.androidtv.tvapprepo, PID: 25606
04-09 18:44:29.854 25606 25606 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'byte[] com.android.volley.NetworkResponse.data' on a null object reference
04-09 18:44:29.854 25606 25606 E AndroidRuntime: 	at news.androidtv.tvapprepo.utils.GenerateShortcutHelper$6.onError(GenerateShortcutHelper.java:179)
04-09 18:44:29.854 25606 25606 E AndroidRuntime: 	at news.androidtv.tvapprepo.utils.ShortcutPostTask$2.onErrorResponse(ShortcutPostTask.java:87)
04-09 18:44:29.854 25606 25606 E AndroidRuntime: 	at com.sketchproject.infogue.modules.VolleyMultipartRequest.deliverError(VolleyMultipartRequest.java:141)
04-09 18:44:29.854 25606 25606 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
04-09 18:44:29.854 25606 25606 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
04-09 18:44:29.854 25606 25606 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
04-09 18:44:29.854 25606 25606 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
04-09 18:44:29.854 25606 25606 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6628)
04-09 18:44:29.854 25606 25606 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-09 18:44:29.854 25606 25606 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
04-09 18:44:29.854 25606 25606 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
04-09 18:44:29.890  3731  4102 W ActivityManager:   Force finishing activity news.androidtv.tvapprepo/.activities.MainActivity
04-09 18:44:29.892 25606 25606 I Process : Sending signal. PID: 25606 SIG: 9
04-09 18:44:29.899  3731  3747 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
04-09 18:44:29.899  3731  3747 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
04-09 18:44:29.946  3731  3795 W InputDispatcher: channel 'dbd9388 news.androidtv.tvapprepo/news.androidtv.tvapprepo.activities.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-09 18:44:29.946  3731  3795 E InputDispatcher: channel 'dbd9388 news.androidtv.tvapprepo/news.androidtv.tvapprepo.activities.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-09 18:44:29.946  3731  3795 W InputDispatcher: channel '46e4239 Toast (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-09 18:44:29.946  3731  3795 E InputDispatcher: channel '46e4239 Toast (server)' ~ Channel is unrecoverably broken and will be disposed!
04-09 18:44:29.949  4536  4549 D ControllerMapper_S: Client: news.androidtv.tvapprepo died and unregistered
04-09 18:44:29.950  3731  4509 I WindowManager: WIN DEATH: Window{dbd9388 u0 news.androidtv.tvapprepo/news.androidtv.tvapprepo.activities.MainActivity}
04-09 18:44:29.950  3731  4509 W InputDispatcher: Attempted to unregister already unregistered input channel 'dbd9388 news.androidtv.tvapprepo/news.androidtv.tvapprepo.activities.MainActivity (server)'
04-09 18:44:29.950  4536  4536 D ControllerMapper_S: news.androidtv.tvapprepo binder died, Current App:Request App [news.androidtv.tvapprepo 1920X1080]
04-09 18:44:29.950  3731  3881 I ActivityManager: Process news.androidtv.tvapprepo (pid 25606) has died: fore TOP 
04-09 18:44:29.957  3731  3878 I WindowManager: WIN DEATH: Window{46e4239 u0 Toast}
04-09 18:44:29.957  3731  3878 W InputDispatcher: Attempted to unregister already unregistered input channel '46e4239 Toast (server)'
04-09 18:44:29.959  3731  3907 I WindowManager: WIN DEATH: Window{55692da u0 news.androidtv.tvapprepo/news.androidtv.tvapprepo.activities.MainActivity EXITING}
```
