### ISSUE TITLE
Crashes on Bravia TV (stock launcher, Android 9)

### ISSUE THREAD

**Issue by pkirkovsky** [ITVlab/TvAppRepo#81]
App crashes right after trying to create the shortcut.
Device Info:
Android 9
Patch level January 5 2022
Kernel 4.9.125 #1 Tue Jul 25 10:43:46 JST 2023
Build BRAVIA_ATV2_UC-user 9 PTT1.190515.001.S54 672201 release-keys

ADB logs:
```
10-21 17:26:04.726 10717 10717 I cr_LibraryLoader: Loaded native library version number "81.0.4044.111"
10-21 17:26:04.795  2181  2198 I ActivityManager: Start proc 10991:com.google.android.webview:sandboxed_process0/u0i7 for webview_service news.androidtv.tvapprepo.playstore/org.chromium.content.app.SandboxedProcessService0
10-21 17:26:04.800 10991 10991 W dboxed_process: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
10-21 17:26:04.803 10991 10991 E dboxed_process: Not starting debugger since process cannot load the jdwp agent.
10-21 17:26:04.873 10991 10991 I cr_ChildProcessService: Creating new ChildProcessService pid=10991
10-21 17:26:05.137 10717 10717 I Ads     : Starting ad request.
10-21 17:26:05.138 10717 10717 I Ads     : Use AdRequest.Builder.addTestDevice("5744F420E19BF67C5DE2B82718910539") to get test ads on this device.
10-21 17:26:05.167 10717 10717 D GenerateShortcutHelper: Loading ad
10-21 17:26:05.197 10717 10717 D ShortcutPostTask: {}
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: --apiclient-1729556765197
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: Content-Disposition: form-data; name="app_name"
10-21 17:26:05.206 10717 10717 D ShortcutPostTask:
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: F-Droid
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: --apiclient-1729556765197
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: Content-Disposition: form-data; name="app_package"
10-21 17:26:05.206 10717 10717 D ShortcutPostTask:
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: org.fdroid.fdroid
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: --apiclient-1729556765197
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: Content-Disposition: form-data; name="unique"
10-21 17:26:05.206 10717 10717 D ShortcutPostTask:
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: false
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: --apiclient-1729556765197
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: Content-Disposition: form-data; name="json"
10-21 17:26:05.206 10717 10717 D ShortcutPostTask:
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: true
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: --apiclient-1729556765197
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: Content-Disposition: form-data; name="app_category"
10-21 17:26:05.206 10717 10717 D ShortcutPostTask:
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: apps
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: --apiclient-1729556765197--
10-21 17:26:05.206 10717 10717 D ShortcutPostTask: multipart/form-data;boundary=apiclient-1729556765197
10-21 17:26:05.221 10717 11028 E Volley  : [648] NetworkDispatcher.run: Unhandled exception java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
10-21 17:26:05.221 10717 11028 E Volley  : java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
10-21 17:26:05.221 10717 11028 E Volley  : 	at android.widget.Toast$TN.<init>(Toast.java:393)
10-21 17:26:05.221 10717 11028 E Volley  : 	at android.widget.Toast.<init>(Toast.java:117)
10-21 17:26:05.221 10717 11028 E Volley  : 	at android.widget.Toast.makeText(Toast.java:280)
10-21 17:26:05.221 10717 11028 E Volley  : 	at android.widget.Toast.makeText(Toast.java:270)
10-21 17:26:05.221 10717 11028 E Volley  : 	at android.widget.Toast.makeText(Toast.java:307)
10-21 17:26:05.221 10717 11028 E Volley  : 	at news.androidtv.tvapprepo.utils.ShortcutPostTask$3.getByteData(ShortcutPostTask.java:129)
10-21 17:26:05.221 10717 11028 E Volley  : 	at com.sketchproject.infogue.modules.VolleyMultipartRequest.getBody(VolleyMultipartRequest.java:98)
10-21 17:26:05.221 10717 11028 E Volley  : 	at com.android.volley.toolbox.HurlStack.addBodyIfExists(HurlStack.java:260)
10-21 17:26:05.221 10717 11028 E Volley  : 	at com.android.volley.toolbox.HurlStack.setConnectionParametersForRequest(HurlStack.java:234)
10-21 17:26:05.221 10717 11028 E Volley  : 	at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:107)
10-21 17:26:05.221 10717 11028 E Volley  : 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
10-21 17:26:05.221 10717 11028 E Volley  : 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
10-21 17:26:05.223  2181  3425 D ConnectivityService: requestNetwork for uid/pid:10196/10717 NetworkRequest [ TRACK_DEFAULT id=75, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10196] ]
10-21 17:26:05.227  2181  2304 D WIFI    : got request NetworkRequest [ TRACK_DEFAULT id=75, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10196] ] with score 70
10-21 17:26:05.227  2181  2304 D WIFI_UT : got request NetworkRequest [ TRACK_DEFAULT id=75, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10196] ] with score 70
10-21 17:26:05.227  2181  2329 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=75, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10196] ] with score 70
10-21 17:26:05.241  1400  2576 E BufferQueueProducer: [news.androidtv.tvapprepo.playstore/news.androidtv.tvapprepo.activities.MainActivity#1] disconnect: not connected (req=1)
10-21 17:26:05.241 10717 10934 W libEGL  : EGLNativeWindowType 0x93255008 disconnect failed
10-21 17:26:05.255 10717 10717 I Choreographer: Skipped 60 frames!  The application may be doing too much work on its main thread.
10-21 17:26:05.263  2181  8897 E WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
10-21 17:26:05.272 10717 10717 E ShortcutPostTask: Error: java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
10-21 17:26:05.272 10717 10717 D ShortcutPostTask: com.android.volley.VolleyError: java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
10-21 17:26:05.290 10717 10717 D AndroidRuntime: Shutting down VM
10-21 17:26:05.292 10717 10717 E AndroidRuntime: FATAL EXCEPTION: main
10-21 17:26:05.292 10717 10717 E AndroidRuntime: Process: news.androidtv.tvapprepo.playstore, PID: 10717
10-21 17:26:05.292 10717 10717 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'byte[] com.android.volley.NetworkResponse.data' on a null object reference
10-21 17:26:05.292 10717 10717 E AndroidRuntime: 	at news.androidtv.tvapprepo.utils.GenerateShortcutHelper$6.onError(GenerateShortcutHelper.java:179)
10-21 17:26:05.292 10717 10717 E AndroidRuntime: 	at news.androidtv.tvapprepo.utils.ShortcutPostTask$2.onErrorResponse(ShortcutPostTask.java:87)
10-21 17:26:05.292 10717 10717 E AndroidRuntime: 	at com.sketchproject.infogue.modules.VolleyMultipartRequest.deliverError(VolleyMultipartRequest.java:141)
10-21 17:26:05.292 10717 10717 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
10-21 17:26:05.292 10717 10717 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
10-21 17:26:05.292 10717 10717 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-21 17:26:05.292 10717 10717 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
10-21 17:26:05.292 10717 10717 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
10-21 17:26:05.292 10717 10717 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-21 17:26:05.292 10717 10717 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-21 17:26:05.292 10717 10717 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-21 17:26:05.341  1400  2177 W SurfaceFlinger: Attempting to set client state on removed layer: news.androidtv.tvapprepo.playstore/news.androidtv.tvapprepo.activities.MainActivity#1
10-21 17:26:05.341  1400  2177 W SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - Task=23051#0
10-21 17:26:05.342  1400  2177 W SurfaceFlinger: Attempting to destroy on removed layer: news.androidtv.tvapprepo.playstore/news.androidtv.tvapprepo.activities.MainActivity#1
10-21 17:26:05.342  1400  2177 W SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - Task=23051#0
10-21 17:26:05.347 10717 11035 I prepo.playstor: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzeho>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/customtabs/CustomTabsServiceConnection;
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at boolean com.google.android.gms.internal.zznr.zzk(android.content.Context) ((null):-1)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at void com.google.android.gms.internal.zzaci.<init>(android.content.Context, com.google.android.gms.internal.zzach) ((null):-1)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at java.lang.Object com.google.android.gms.internal.zzack.call() ((null):-1)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at void com.google.android.gms.internal.zzahc.run() ((null):-1)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:458)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1167)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:641)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at void java.lang.Thread.run() (Thread.java:764)
10-21 17:26:05.347 10717 11035 I prepo.playstor: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.customtabs.CustomTabsServiceConnection" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/news.androidtv.tvapprepo.playstore-pvI-9JoFh-fuYg1nOWp9xA==/base.apk"],nativeLibraryDirectories=[/data/app/news.androidtv.tvapprepo.playstore-pvI-9JoFh-fuYg1nOWp9xA==/lib/arm, /system/lib, /system/vendor/lib]]
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at boolean com.google.android.gms.internal.zznr.zzk(android.content.Context) ((null):-1)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at void com.google.android.gms.internal.zzaci.<init>(android.content.Context, com.google.android.gms.internal.zzach) ((null):-1)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at java.lang.Object com.google.android.gms.internal.zzack.call() ((null):-1)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at void com.google.android.gms.internal.zzahc.run() ((null):-1)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:458)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
10-21 17:26:05.347 10717 11035 I prepo.playstor:   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1167)
10-21 17:26:05.350 10717 11035 I prepo.playstor:   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:641)
10-21 17:26:05.356 10717 11035 I prepo.playstor:   at void java.lang.Thread.run() (Thread.java:764)
10-21 17:26:05.358 10717 11035 I prepo.playstor:
10-21 17:26:05.360 10717 11035 I prepo.playstor: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzeho>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/customtabs/CustomTabsServiceConnection;
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at boolean com.google.android.gms.internal.zznr.zzk(android.content.Context) ((null):-1)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at void com.google.android.gms.internal.zzaci.<init>(android.content.Context, com.google.android.gms.internal.zzach) ((null):-1)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at java.lang.Object com.google.android.gms.internal.zzack.call() ((null):-1)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at void com.google.android.gms.internal.zzahc.run() ((null):-1)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:458)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1167)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:641)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at void java.lang.Thread.run() (Thread.java:764)
10-21 17:26:05.360 10717 11035 I prepo.playstor: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.customtabs.CustomTabsServiceConnection" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/news.androidtv.tvapprepo.playstore-pvI-9JoFh-fuYg1nOWp9xA==/base.apk"],nativeLibraryDirectories=[/data/app/news.androidtv.tvapprepo.playstore-pvI-9JoFh-fuYg1nOWp9xA==/lib/arm, /system/lib, /system/vendor/lib]]
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at boolean com.google.android.gms.internal.zznr.zzk(android.content.Context) ((null):-1)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at void com.google.android.gms.internal.zzaci.<init>(android.content.Context, com.google.android.gms.internal.zzach) ((null):-1)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at java.lang.Object com.google.android.gms.internal.zzack.call() ((null):-1)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at void com.google.android.gms.internal.zzahc.run() ((null):-1)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:458)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1167)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:641)
10-21 17:26:05.360 10717 11035 I prepo.playstor:   at void java.lang.Thread.run() (Thread.java:764)
10-21 17:26:05.360 10717 11035 I prepo.playstor:
10-21 17:26:05.560  2181  3425 W ActivityManager:   Force finishing activity news.androidtv.tvapprepo.playstore/news.androidtv.tvapprepo.activities.MainActivity
10-21 17:26:05.574 10717 10717 I Process : Sending signal. PID: 10717 SIG: 9
10-21 17:26:05.649  2181  2289 W InputDispatcher: channel '3b470cb news.androidtv.tvapprepo.playstore/news.androidtv.tvapprepo.activities.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-21 17:26:05.650  2181  2289 E InputDispatcher: channel '3b470cb news.androidtv.tvapprepo.playstore/news.androidtv.tvapprepo.activities.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-21 17:26:05.663  2181  2289 W InputDispatcher: channel '1ef534e Toast (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-21 17:26:05.664  2181  2289 E InputDispatcher: channel '1ef534e Toast (server)' ~ Channel is unrecoverably broken and will be disposed!
10-21 17:26:05.667  2181  8897 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=75, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10196] ], android.os.BinderProxy@a8f7a67)
10-21 17:26:05.667  2181  3421 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=76, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND Unwanted:  Uid: 10196] ], android.os.BinderProxy@90cb014)
10-21 17:26:05.668  2181  2307 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=75, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10196] ] (release request)
10-21 17:26:05.668  2181 10669 I ActivityManager: Process news.androidtv.tvapprepo.playstore (pid 10717) has died: fore TOP```

**Comment by kotaru34** [comment]
same issue, android 9, mi box 4s.
Trying to create wavelet shortcut
